name: aims2frontend
description: "AIMS Frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.3
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  provider: ^6.1.5+1
  get_storage: ^2.1.1
  path_provider: ^2.1.5

  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5

  barcode: ^2.2.9
  encrypt: ^5.0.3
  barcode_image: ^2.0.3
  image: ^4.5.4

  file_picker: ^10.3.8
  qr_flutter: ^4.1.0

  barcode_widget: ^2.0.4

  uuid: ^4.5.2
  intl: ^0.20.2

  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^1.1.1

  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# ðŸ‘‡ THIS MUST BE TOP-LEVEL (NOT inside dev_dependencies)
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/aims2landinglogo.png"
    icon_size: 256


  macos:
    generate: true
    image_path: "assets/aims2landinglogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/App_Logo.jpg
    - assets/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
